language: node_js
node_js: node

cache:
  directories:
  - node_modules

script:
- npm run build
- npm test

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./tools/deploy.sh
  on:
    branch: master
    
branches:
  only:
  - master

# Need to configure env variables in Travis CI settings
# * GH_TOKEN : personal access token with read/write access to the repo
# * DEPLOY_TARGET_BRANCH : branch being pushed to after successful build
